### ISSUE TITLE
Multiple Cloud Anchors

### ISSUE THREAD

**Issue by adityaab14** [googlecodelabs/arcore-cloud-anchors#10]
Please help me with hosting multiple cloud anchors with a memory array to store the short code of all the anchors

**Comment by adityaab14** [comment]
Such that many short codes are projected and in the receiver end each short code an be individually entered to retrieve the respective cloud anchor.

**Comment by asadullahnaweed** [comment]
This issue tracker only exists to point out bugs in the codelab itself.

Nevertheless, here's one possible solution to your problem:
The short codes can very easily be stored in a string array in SharedPreferences, and you can use a DialogFragment to present a list of available short codes to the user to select from.
