### ISSUE TITLE
CodeLabs Documentation Error

### ISSUE THREAD

**Issue by syntax-error404** [googlecodelabs/arcore-cloud-anchors#11]
In Part two of the [CodeLabs tutorial](https://codelabs.developers.google.com/codelabs/arcore-cloud-anchors/#2) within the code snippet for `OnArPlaneTap` the code reads `setNewAnchor(newAnchor);`. I think this should be chnaged to `setNewAnchor(anchor);`. The github file [Work.Java](https://github.com/googlecodelabs/arcore-cloud-anchors/blob/master/work/src/main/java/com/google/ar/core/codelab/cloudanchor/CloudAnchorFragment.java) confirms my thoery on line 83. 

Thank you all for all the work and support you put into this!

**Comment by asadullahnaweed** [comment]
Thank you so much for pointing this out! Fixed.
