### ISSUE TITLE
Typo: "Declare *INTERNET permissions"

### ISSUE THREAD

**Issue by bounty-torn** [googlecodelabs/arcore-cloud-anchors#2]
Here: https://codelabs.developers.google.com/codelabs/arcore-cloud-anchors/#2

- Heading says "Declare INTENRET permissions" but should say "Declare INTERNET permissions"
![image](https://user-images.githubusercontent.com/2023216/40953422-89f4f41a-6834-11e8-921e-9ef93eb6ce04.png)

- Instances of "internet" should say "Internet" as reference to the proper noun

**Comment by asadullahnaweed** [comment]
Done!
