### ISSUE TITLE
Issue with modifying handleTaponDraw method

### ISSUE THREAD

**Issue by econiglio** [googlecodelabs/arcore-cloud-anchors#3]
Direction: 

Also modify the handleTapOnDraw() method: Add an appAnchorState == AppAnchorState.NONE extra condition to the if-block:

private void handleTapOnDraw(TrackingState currentTrackingState, Frame currentFrame) {
    synchronized (singleTapLock) {
      synchronized (anchorLock) {
        if (anchor == null
           && queuedSingleTap != null
            && currentTrackingState == TrackingState.TRACKING
            && appAnchorState == AppAnchorState.NONE) { // Add this condition.
          ...

Actual Code:

private void handleTapOnDraw(TrackingState currentTrackingState, Frame currentFrame) {
        synchronized (singleTapAnchorLock) {
            if (anchor == null
                    && queuedSingleTap != null
                    && currentTrackingState == TrackingState.TRACKING);
                    && appAnchorState == AppAnchorState.NONE); { // Add this condition.{
                for (HitResult hit : currentFrame.hitTest(queuedSingleTap)) {
                    if (shouldCreateAnchorWithHit(hit)) {
                        Anchor newAnchor = session.hostCloudAnchor(hit.createAnchor());
                        setNewAnchor(newAnchor);

                        // Add some UI to show you that the anchor is being hosted.
                        appAnchorState = AppAnchorState.HOSTING; // Add this line.
                        snackbarHelper.showMessage(this, "Now hosting anchor..."); // Add this line.
                        break;
                    }
                }
            }
            queuedSingleTap = null;
        }
    }

**Comment by asadullahnaweed** [comment]
All of this code has been removed, and the codelab samples now use Sceneform for simplified rendering code. Please give it another shot!
