### ISSUE TITLE
Update example with "singleTapAnchorLock"

### ISSUE THREAD

**Issue by bounty-torn** [googlecodelabs/arcore-cloud-anchors#4]
The documentation currently shows:

![image](https://user-images.githubusercontent.com/2023216/41118848-06ede4e6-6a46-11e8-9e58-f0aebdecca2d.png)

But the actual code shows:

![image](https://user-images.githubusercontent.com/2023216/41118896-29d81e40-6a46-11e8-8640-3401b48cbec8.png)

**Comment by asadullahnaweed** [comment]
This code has been updated. The drawing code is now all based on Sceneform, and is significantly simpler. Please try the codelab again!
