### ISSUE TITLE
Part 1: Update ARCore version to 1.4 

### ISSUE THREAD

**Issue by sorianog** [googlecodelabs/arcore-cloud-anchors#5]
[Tutorial ](https://codelabs.developers.google.com/codelabs/arcore-cloud-anchors/#1) has it at 1.2 while the current version is 1.4.

Additionally, I am facing the current issue: https://github.com/google-ar/arcore-android-sdk/issues/560

**Comment by asadullahnaweed** [comment]
Updated to 1.8.0
