### ISSUE TITLE
NullPointerException in Firebase Options

### ISSUE THREAD

**Issue by MohsenneChaverdie** [googlecodelabs/arcore-cloud-anchors#6]
I cannot connect my database to the app. Android Emulator cannot run the app. I receive the below error:

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.FirebaseOptions com.google.firebase.FirebaseApp.getOptions()' on a null object reference`

what do you suggest me to do?

- I opened part 4, added my API to Manifest, and through Firebase Assistent set up my database.

**Comment by asadullahnaweed** [comment]
The codelab has been updated. Please try it again. The Firebase issue should go away.
